--- 
- name: install apache & php & mysql
  hosts: all
  become: true
  become_user: root
  gather_facts: true

  tasks:
   - name: “Install apache”
     package: name=httpd state=present
   - name: “Install apache2-php5”
     package: name=php state=present

